todoList/home/urls.py
from django.urls import path
from .import views

urlpatterns = [
    path('', views.home, name='home'),
    path('tasks', views.tasks, name='tasks'),
    path('complete-task/<str:pk>/', views.CompleteTask, name='complete-task'),
    path('update-task/<str:pk>/', views.Update, name='update-task'),
    path('delete-task/<str:pk>/', views.Delete, name='delete-task'),

]

todoList/todoList/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.models import Group

# Dango admin header customization
# admin.site.unregister(Group)
admin.site.site_header = "Developer: Simeon"
admin.site.site_title = "Log in to this Portal"
admin.site.index_title = "Welcome to Simeon's Dashboard"


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('todo/', include('todoapp.urls'))
]

todoList/todoapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.alltodos, name='alltodos'),
    path('delete<int:pk>', views.Delete, name='delete'),
    path('update<int:pk>', views.Update, name='update'),
]

todoList/home/models.py
from django.db import models


# Create your models here.


class Task(models.Model):
    objects = None
    taskTitle = models.CharField(max_length=30)
    taskDesc = models.TextField()
    complete = models.BooleanField(default=False)
    time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.taskTitle

todoList/todoapp/models.py
from django.db import models


# Create your models here.
class Blue_todo(models.Model):
    task = models.CharField(max_length=50)

    def __str__(self):
        return self.task

todoList/home/forms.py
from django import forms
from .models import Task


class TaskForm(forms.ModelForm):
    content = forms.CharField(label='', widget=forms.TextInput(
        attrs={'placeholder': 'Add task here...'}))

    class Meta:
        model = Task
        fields = ['content']


class UpdateTaskForm(forms.ModelForm):
    complete = forms.CharField(label='', widget=forms.TextInput(
        attrs={'placeholder': 'Tick task here...'}))

    class Meta:
        model = Task
        fields = '__all__'

todoList/todoapp/forms.py
from django import forms
from .models import Blue_todo


class TodoForm(forms.ModelForm):

    class Meta:
        model = Blue_todo
        fields = ['task', ]

todoList/home/views.py
from django.shortcuts import render, redirect
from .forms import TaskForm, UpdateTaskForm
from .models import Task


# Create your views here.


def home(request):
    context = {'success': True, 'name': 'Simeon'}
    if request.method == "POST":
        # Handle the form here
        title = request.POST['title']
        desc = request.POST['desc']
        complete_task = Task.objects.filter(complete=True)
        # print(title, desc)
        ins = Task(taskTitle=title, taskDesc=desc)
        ins.save()
        context = {'success': True,
                   'complete_task': complete_task,
                   'form': TaskForm}
    return render(request, "index.html", context)


def tasks(request):
    allTasks = Task.objects.all()
    # print(allTasks)
    context = {'tasks': allTasks}
    return render(request, "tasks.html", context)


def Update(request, pk):
    task = Task.objects.get(id=pk)
    updateForm = UpdateTaskForm(instance=task)
    if request.method == 'POST':
        updateForm = UpdateTaskForm(request.POST, instance=task)
        if updateForm.is_valid():
            updateForm.save()
            return redirect('tasks')

    return render(request, 'update.html', {'updateForm': updateForm, })


def Delete(request, pk):
    task = Task.objects.get(id=pk)
    if request.method == 'POST':
        task.delete()
        return redirect('tasks')
    return render(request, 'delete.html', {'item': task, })


def CompleteTask(request, pk):
    task = Task.objects.get(id=pk)
    complete_task = Task.objects.filter(complete=True)
    if request.method == 'POST':
        form = TaskForm
        if complete_task == Task.objects.filter(complete=True):
            form.save()
            return redirect('tasks')

    return render(request, 'complete.html', {'form': form, })

todoList/todoapp/views.py
from django.shortcuts import render, redirect
from .models import Blue_todo
from .forms import TodoForm


# Create your views here.
def alltodos(request):
    tasks = Blue_todo.objects.all()
    form = TodoForm()
    if request.method == 'POST':
        form = TodoForm(request.POST)
        if form.is_valid():
            form.save()
    return render(request, 'alltodo.html', {'tasks': tasks, 'form': form})


def Delete(request, pk):
    task = Blue_todo.objects.get(id=pk)
    if request.method == 'POST':
        task.delete()
        return redirect('alltodos')
    return render(request, 'delete.html', {'item': task})


def Update(request, pk):
    todo = Blue_todo.objects.get(id=pk)
    updateForm = TodoForm(instance=todo)
    if request.method == 'POST':
        updateForm = TodoForm(request.POST, instance=todo)
        if updateForm.is_valid():
            updateForm.save()
            return redirect('alltodos')

    return render(request, 'update.html', {'todo': todo, 'updateForm': updateForm})

todoList/home/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1 shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>{{ tilte }}</title>
</head>
<body>
{% block content %}
{% includ update.html %}
{% includ delete.html %}
{% includ tasks.html %}
{% includ index.html %}

{% endblock content %}
</body>

</html>

todoList/home/templates/delete.html
<h4>Delete Task</h4>
<br>
<div class="row">
    <div class="col-md-6">
        <div class="card card-body bg-danger">
            <div class="alert alert-danger">
                <p>Are you sure you want to delete{{item}}?</p>
                <form action="{% url 'delete-task' item.id %}" method="POST">
                    {% csrf_token %}
                    {{ updateForm }}
                    <a class="btn btn-secondary" href="{% url 'tasks' %}">Cancel</a>
                    <input class="btn btn-danger" type="submit" value="Confirm">
                </form>
            </div>
        </div>
    </div>
</div>

todoList/home/templates/index.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1 shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>index</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="/">TODO HOME - ADD</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/tasks">Tasks<span class="sr-only"></span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/">New Task</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
    {% if success %}
    <div class="alert alert-primary alert dismissible fade show" role="alert">
        <strong>simple success alert—check it out!</strong> form submitted :
        <button type="button" class="close" data-dismiss="alert" aria-label="close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>

    {% endif %}
<div class="container my-3">
    <h2 class="text-center bg-secondary text-warning text-bold">Welcome to Todos List - Add a task</h2>
    <div class="bg-light">
        <label for="exampleColorInput" class="form-label">Color picker</label>
        <input type="color" class="form-control form-control-color" id="exampleColorInput" value="#563d7c" title="Choose your color">
    </div>
    <form action="/" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="title">Task Title</label>
            <input type="text" class="form-control" id="title" name="title" aria-describedby="emailHelp">
        </div>
        <div class="form-group">
            <label for="desc">Task Description</label>
            <textarea class="form-control" name="desc" id="desc" cols="20" rows="8"></textarea>
        </div>
        <div class="container my-3">
        <button type="submit" class="btn btn-primary" typeof="hover">Submit</button>
        </div>
    </form>
</div>

<!-- Optional JavaScript; choose one of the two! -->

<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>

<!-- Option 2: Separate Popper and Bootstrap JS -->
<!--
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
-->
</body>
 <footer class="text-center text-white bg-dark my-0 py-3 fixed-bottom" style="background-color: Navy">
    <!-- Grid container -->
    <div class="container p-2">
      <!-- Section: Images -->
      <section class="">
        <div class="row">
          <div class="col-lg-2 col-md-12 mb-4 mb-md-0">
            <div
                 class="bg-image hover-overlay ripple shadow-1-strong rounded"
                 data-ripple-color="light"
                 >
             {% load static %}<img src="{% static '/images/slide 1.jpg/' %}" class="d-block w-100 h-50" alt="...">
              <a href="#!">
                <div
                     class="mask"
                     style="background-color: rgba(251, 251, 251, 0.2);"
                     ></div>
              </a>
            </div>
          </div>
          <div class="col-lg-2 col-md-12 mb-4 mb-md-0">
            <div
                 class="bg-image hover-overlay ripple shadow-1-strong rounded"
                 data-ripple-color="light"
                 >
              {% load static %}<img src="{% static '/images/slide 2.jpg/' %}" class="d-block w-100 h-50" alt="...">
              <a href="#!">
                <div
                     class="mask"
                     style="background-color: rgba(251, 251, 251, 0.2);"
                     ></div>
              </a>
            </div>
          </div>
          <div class="col-lg-2 col-md-12 mb-4 mb-md-0">
            <div
                 class="bg-image hover-overlay ripple shadow-1-strong rounded"
                 data-ripple-color="light"
                 >
             {% load static %}<img src="{% static '/images/slide 3.jpg/' %}" class="d-block w-100 h-50" alt="...">
              <a href="#!">
                <div
                     class="mask"
                     style="background-color: rgba(251, 251, 251, 0.2);"
                     ></div>
              </a>
            </div>
          </div>
          <div class="col-lg-2 col-md-12 mb-4 mb-md-0">
            <div
                 class="bg-image hover-overlay ripple shadow-1-strong rounded"
                 data-ripple-color="light"
                 >
              {% load static %}<img src="{% static '/images/slide 4.jpg/' %}" class="d-block w-100 h-50" alt="...">
              <a href="#!">
                <div
                     class="mask"
                     style="background-color: rgba(251, 251, 251, 0.2);"
                     ></div>
              </a>
            </div>
          </div>
          <div class="col-lg-2 col-md-12 mb-4 mb-md-0">
            <div
                 class="bg-image hover-overlay ripple shadow-1-strong rounded"
                 data-ripple-color="light"
                 >
              {% load static %}<img src="{% static '/images/slide 5.jpg/' %}" class="d-block w-100 h-50" alt="...">
              <a href="#!">
                <div
                     class="mask"
                     style="background-color: rgba(251, 251, 251, 0.2);"
                     ></div>
              </a>
            </div>
          </div>
          <div class="col-lg-2 col-md-12 mb-4 mb-md-0">
            <div
                 class="bg-image hover-overlay ripple shadow-1-strong rounded"
                 data-ripple-color="light"
                 >
              {% load static %}<img src="{% static '/images/slide 6.jpg/' %}" class="d-block w-100 h-50" alt="...">
              <a href="#!">
                <div
                     class="mask"
                     style="background-color: rgba(251, 251, 251, 0.2);"
                     ></div>
              </a>
            </div>
          </div>

        </div>
      </section>
      <!-- Section: Images -->
    </div>
    <!-- Grid container -->

    <!-- Copyright -->
    <div class="text-center p-1" style="background-color: rgba(0, 0, 0, 0.2);">
      © 2022 Copyright:
      <a class="text-white" href="https://unsplash.com/"></a>
    </div>
    <!-- Copyright -->
  </footer>
</html>

todoList/home/templates/tasks.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1 shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Tasks</title>
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="/">TODO TASK - LIST</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/">New Task<span class="sr-only"></span></a>
                <li class="nav-item">
                    <a class="nav-link" href="/tasks">Tasks</a>
                </li>
            </ul>
            <form class="d-flex">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>
<div class="container my-3">
    <h2 class="text-center bg-dark text-warning">Todos List- All tasks</h2>
    <div class="border p-3">
        <form action="" method="POST">
            {% csrf_token %}
            {{ form }}
            {{ updateForm }}
            {{ CompleteTaskForm }}
        </form>
        <hr>
        <table class="table">
            <table class="table table-info table table-dark table-hover text-warning">
                <thead>
                <tr>
                    <th scope="col">Task item No.</th>
                    <th scope="col">Task Title</th>
                    <th scope="col">Task Description</th>
                    <th scope="col">Status</th>
                    <th scope="col">Update</th>
                    <th scope="col">Delete</th>
                </tr>
                </thead>
                <tbody>
                {% for task in tasks %}
                <tr>
                    <th scope="row">{{forloop.counter}}</th>
                    <td>{{task.taskTitle}}</td>
                    <td>{{task.taskDesc}}</td>
                    <td>{{task.complete}}</td>
                        <div class="col-md-8">
                            {% if task.complete == True %}

                            {% endif %}
                        </div>
                    <td><a href="{% url 'update-task' task.id %}"><button type="button" class="btn btn-warning">Edit</button></a></td>
                    <td><a href="{% url 'delete-task' task.id %}"><button type="button" class="btn btn-danger">Delete</button></a></td>
                </tr>
    </div>
              {% endfor %}
            <p>
                <a href="/">
                    <button type="button" class="btn btn-dark bg-secondary">Add a Task</button>
                </a>
            </p>
            </table>




<!-- Optional JavaScript; choose one of the two! -->

<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>

<!-- Option 2: Separate Popper and Bootstrap JS -->
<!--
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
-->
</body>
<!-- Remove the container if you want to extend the Footer to full width. -->
<!--<div class="container my-5">-->

<!-- Remove the container if you want to extend the Footer to full width. -->
<!--<div class="container my-5">-->

 <footer class="text-center text-white bg-dark my-0 py-3 fixed-bottom" style="background-color: Navy">
    <!-- Grid container -->
    <div class="container p-2">
      <!-- Section: Images -->
      <section class="">
        <div class="row">
          <div class="col-lg-2 col-md-12 mb-4 mb-md-0">
            <div
                 class="bg-image hover-overlay ripple shadow-1-strong rounded"
                 data-ripple-color="light"
                 >
             {% load static %}<img src="{% static '/images/slide 7.jpg/' %}" class="d-block w-100 h-50" alt="...">
              <a href="#!">
                <div
                     class="mask"
                     style="background-color: rgba(251, 251, 251, 0.2);"
                     ></div>
              </a>
            </div>
          </div>
          <div class="col-lg-2 col-md-12 mb-4 mb-md-0">
            <div
                 class="bg-image hover-overlay ripple shadow-1-strong rounded"
                 data-ripple-color="light"
                 >
              {% load static %}<img src="{% static '/images/slide 8.jpg/' %}" class="d-block w-100 h-50" alt="...">
              <a href="#!">
                <div
                     class="mask"
                     style="background-color: rgba(251, 251, 251, 0.2);"
                     ></div>
              </a>
            </div>
          </div>
          <div class="col-lg-2 col-md-12 mb-4 mb-md-0">
            <div
                 class="bg-image hover-overlay ripple shadow-1-strong rounded"
                 data-ripple-color="light"
                 >
             {% load static %}<img src="{% static '/images/slide 9.jpg/' %}" class="d-block w-100 h-50" alt="...">
              <a href="#!">
                <div
                     class="mask"
                     style="background-color: rgba(251, 251, 251, 0.2);"
                     ></div>
              </a>
            </div>
          </div>
          <div class="col-lg-2 col-md-12 mb-4 mb-md-0">
            <div
                 class="bg-image hover-overlay ripple shadow-1-strong rounded"
                 data-ripple-color="light"
                 >
              {% load static %}<img src="{% static '/images/slide 10.jpg/' %}" class="d-block w-100 h-50" alt="...">
              <a href="#!">
                <div
                     class="mask"
                     style="background-color: rgba(251, 251, 251, 0.2);"
                     ></div>
              </a>
            </div>
          </div>
          <div class="col-lg-2 col-md-12 mb-4 mb-md-0">
            <div
                 class="bg-image hover-overlay ripple shadow-1-strong rounded"
                 data-ripple-color="light"
                 >
              {% load static %}<img src="{% static '/images/slide 11.jpg/' %}" class="d-block w-100 h-50" alt="...">
              <a href="#!">
                <div
                     class="mask"
                     style="background-color: rgba(251, 251, 251, 0.2);"
                     ></div>
              </a>
            </div>
          </div>
          <div class="col-lg-2 col-md-12 mb-4 mb-md-0">
            <div
                 class="bg-image hover-overlay ripple shadow-1-strong rounded"
                 data-ripple-color="light"
                 >
              {% load static %}<img src="{% static '/images/slide 12.jpg/' %}" class="d-block w-100 h-50" alt="...">
              <a href="#!">
                <div
                     class="mask"
                     style="background-color: rgba(251, 251, 251, 0.2);"
                     ></div>
              </a>
            </div>
          </div>

        </div>
      </section>
      <!-- Section: Images -->
    </div>
    <!-- Grid container -->

    <!-- Copyright -->
    <div class="text-center p-1" style="background-color: rgba(0, 0, 0, 0.2);">
      © 2022 Copyright:
      <a class="text-white" href="https://unsplash.com/"></a>
    </div>
    <!-- Copyright -->
  </footer>
</html>

todoList/home/templates/update.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
  </head>
  <body>


<b>Update Task</b>
<br>
<div class="row">
    <div class="col-md-6">
        <div class="card card-body bg-info">
			<p><a class="btn btn-sm btn-success btn-hover" href="{% url 'tasks' %}">Back to list</a></p>

			<form action="" method="POST">
				{{ updateForm.as_p }}
				{{ CompleteTaskForm }}
				{% csrf_token %}
				<a class="btn btn-sm btn-light" href="{% url 'tasks' %}">Update</a>
				<input class="btn btn-sm btn-primary" type="submit" value="Update" name="update">
				<div class="form-row field-complete">
				<div class="checkbox-row">
				<input type="checkbox" name="complete" id="id_complete"><label class="vCheckboxLabel" for="id_complete">Complete</label>
				</div>
				</div>
			</form>
		</div>
	</div>
</div>
</body>
</html>

todoList/todoapp/templates/alltodo.html
<!doctype html>
{% extends 'base.html' %}
{% block content %}

<html lang="en" dir="ltr">
<head>
    <style>
body {background-color: powderblue;}
h1   {color: blue;}
p    {color: red;}

    </style>
    <!-- Required meta tags -->
    <!--    <meta charset="utf-8">-->
    <!--    <meta name="viewport" content="width=device-width, initial-scale=1">-->

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.rtl.min.css"
          integrity="sha384-gXt9imSW0VcJVHezoNQsP+TNrjYXoGcrqBZJpry9zJt8PCQjobwmhMGaDHTASo9N" crossorigin="anonymous">

    <title>Todoapp</title>
    <div class="row">
        <div class="col-md-8">
            <div class="card card-body bg-secondary">
                <header class="bg-primary mx-0 px-0">
                    <h1 class="text-center">Todo List</h1>
                </header>
                <!--        <div class="container fluid mx-8 px-8">-->
                <table class="text-warning table table-dark table-hover mx-8 px-8">

                </table>
                <thead>
                <tbody>

                <tr>
                    <th>Tasks</th>
                    <th>Edit</th>
                    <th>Delete</th>
                </tr>

                <form action="" method="POST">
                    {{form}}
                    {% csrf_token %}
                    <button type="submit" class="btn btn-success btn-block btn-sm">Submit</button>
                </form>
                {% for todo in tasks %}

                <tr>
                    <td>{{todo.task}}</td>
                    <td><a href="{% url 'update' todo.id %}">
                        <button class="btn btn-info btn-block btn-sm">Update</button>
                    </a></td>
                    <td><a href="{% url 'delete' todo.id %}">
                        <button class="btn btn-danger btn-block btn-sm">Delete</button>
                    </a></td>
                </tr>

                {% endfor %}

            </div>
        </div>
    </div>
    {% endblock content %}
</html>

todoList/todoapp/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
  </head>
  <body>
  {% block content %}{% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
  </body>
</html>

todoList/todoapp/templates/delete.html
{% extends 'base.html' %}
{% block content %}
<br>
<div class="row">
    <div class="col-md-6">
        <div class="card card-body bg-danger">
            <h1>Blue Todo List</h1>
            <p> Are you sure you want to delete"{{item}}"?</p>
            <form action="{% url 'delete' item.id %}" method="POST">
                   {% csrf_token %}
                <a href="{%url 'alltodos'%}" class="btn btn-hover btn-info"> Cancel</a>
                <input class="btn btn-hover btn-success" type="submit" value="Confirm">
            </form>
        </div>
    </div>
</div>
{% endblock %}

todoList/todoapp/templates/update.html
{% extends 'base.html' %}
{% block content %}
<br>
<div container="text-warning">
    <div class="row">
        <div class="col-md-6">
            <div class="card card-body bg-info">
                <h1>Blue Todo List</h1>
                <form method="POST">
                    {{updateForm}}
                    {% csrf_token %}
                     <a href="{%url 'alltodos'%}" class="btn btn-hover btn-info"> Cancel</a>
                    <button class="btn btn-secondary btn-hover" type="submit">Edit</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}